### ISSUE TITLE
slice operator does not work.

### ISSUE THREAD

**Issue by yassin-taskin** [plasticityai/magnitude#5]
I get an error when using slice notation on the vector object.

```python
Traceback (most recent call last):
  File magnitude_test.py", line 9, in <module>
    test_list = [vectors[3:20],
  File "pymagnitude\__init__.py", line 1257, in __getitem__
    return_vector=True)
  File "pymagnitude\__init__.py", line 795, in index
    return self._key_for_index_cached(q, return_vector=return_vector)
  File "pymagnitude\third_party\repoze\lru\__init__.py", line 354, in cached_wrapper
    val = func(*args, **kwargs)
  File "pymagnitude\__init__.py", line 276, in _key_for_index_cached
    return self._key_for_index(*args, **kwargs)
  File "pymagnitude\__init__.py", line 670, in _key_for_index
    (int(index + 1),)).fetchall()
TypeError: unsupported operand type(s) for +: 'range' and 'int'
```

The mistake seems to be in the index method

```python
   def index(self, q, return_vector=True):
        """Gets a key for an index or multiple indices."""
        if isinstance(q, list) or isinstance(q, tuple):
            return self._keys_for_indices(q, return_vector=return_vector)
        else:
            return self._key_for_index_cached(q, return_vector=return_vector)
```

This seems to not branch properly since what it gets is a range. The following should work for everything that is iterable. For me it fixes the bug.

```python
    def index(self, q, return_vector=True):
        """Gets a key for an index or multiple indices."""
        if hasattr(q,"__iter__"):
            return self._keys_for_indices(q, return_vector=return_vector)
        else:
            return self._key_for_index_cached(q, return_vector=return_vector)
```

**Comment by AjayP13** [comment]
Ah, that's a good catch, thanks. That's an issue with Python 3's range returning an iterator:

Fixed it on this commit: https://gitlab.com/Plasticity/magnitude/commit/3a73d0b4545e6d7da700c95f0e1c22fbfea3cb5d

and added a test case for slicing.
