### ISSUE TITLE
Not possible to install pymagnitude in multiple python environments

### ISSUE THREAD

**Issue by gauravkmr** [plasticityai/magnitude#53]
```
Collecting pymagnitude
  Using cached https://files.pythonhosted.org/packages/0a/a3/b9a34d22ed8c0ed59b00ff55092129641cdfa09d82f9abdc5088051a5b0c/pymagnitude-0.1.120.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-PBUBVG/pymagnitude/setup.py", line 178, in <module>
        'a+')
    IOError: [Errno 13] Permission denied: '/tmp/magnitude.install'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-PBUBVG/pymagnitude/
```

I am trying to install pymagnitude in conda environment on a linux machine. I also have permission to write in /tmp directory. But seems like if some other user has already installed pymagnitude other users can't install it.
During installion, pymagnitude tries to create magnitude.install file inside /tmp directory but if magnitude.install already exists inside /tmp and some other user is the owner of it, in this case pip install pymagnitude fails with permission issue. 
One possible solution:
```add a random number at the end of the install directory in the /tmp folder.```

**Comment by dunovank** [comment]
I had the same issue. Found a workaround by using the pip executable in the target environment's `bin` subdir, along with the `--no-cache-dir` flag. Not sure if this will get past the permission issue but worth a shot.

```sh
conda install -n  <env_name> pip
~/anaconda3/envs/<env_name>/bin/pip install -U pymagnitude --no-cache-dir
```

**Comment by ehlen** [comment]
This also happened to me when trying to install via pip in a conda environment, and the solution from @dunovank yielded the same error. My fix was to: (a) clone this repo, and cd into the repo's root directory; (b) `$ mkdir tmp` ; (c) edit setup.py line 175 to change `tempfile.gettempdir(),` to `"./tmp",` ; and (d) `$ python3 setup.py install` . I still saw a lot of errors and warnings, but it seems to install OK.... though I also had to install lz4 and xxhash.

Curious, why this?

```
try:
    import pip._internal.pep425tags as pep425tags
    pep425tags.get_supported()
    raise Exception()
except Exception as e:
    import pep425tags
```
