### ISSUE TITLE
cannot import from pymagnitude :module 'pytest' has no attribute 'mark'

### ISSUE THREAD

**Issue by laifi** [plasticityai/magnitude#61]
Hello ,
This error occurs when i try to import from pymagnitude !

>    from pymagnitude import Magnitude
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/__init__.py", line 80, in <module>
    from pymagnitude.third_party.allennlp.commands.elmo import ElmoEmbedder
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/commands/__init__.py", line 8, in <module>
    from allennlp.commands.configure import Configure
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/commands/__init__.py", line 8, in <module>
    from allennlp.commands.configure import Configure
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/commands/configure.py", line 25, in <module>
    from allennlp.common.configuration import configure, Config, render_config
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/common/configuration.py", line 20, in <module>
    from allennlp.data.iterators import DataIterator
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/data/__init__.py", line 3, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/data/dataset_readers/dataset_reader.py", line 6, in <module>
    from allennlp.data.instance import Instance
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/data/instance.py", line 5, in <module>
    from allennlp.data.fields.field import Field
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/data/fields/__init__.py", line 11, in <module>
    from allennlp.data.fields.knowledge_graph_field import KnowledgeGraphField
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/data/fields/knowledge_graph_field.py", line 18, in <module>
    from allennlp.data.token_indexers.token_indexer import TokenIndexer
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/data/token_indexers/__init__.py", line 7, in <module>
    from allennlp.data.token_indexers.dep_label_indexer import DepLabelIndexer
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/data/token_indexers/dep_label_indexer.py", line 10, in <module>
    from allennlp.data.tokenizers.token import Token
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/data/tokenizers/__init__.py", line 9, in <module>
    from allennlp.data.tokenizers.word_tokenizer import WordTokenizer
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/data/tokenizers/word_tokenizer.py", line 11, in <module>
    from allennlp.data.tokenizers.word_stemmer import WordStemmer, PassThroughWordStemmer
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/pymagnitude/third_party/allennlp/data/tokenizers/word_stemmer.py", line 3, in <module>
    from nltk.stem import PorterStemmer as NltkPorterStemmer
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/nltk/__init__.py", line 143, in <module>
    from nltk.chunk import *
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/nltk/chunk/__init__.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.parse import ParserI
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/nltk/parse/__init__.py", line 100, in <module>
    from nltk.parse.transitionparser import TransitionParser
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/nltk/parse/transitionparser.py", line 22, in <module>
    from sklearn.datasets import load_svmlight_file
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/datasets/__init__.py", line 22, in <module>
    from .twenty_newsgroups import fetch_20newsgroups
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/datasets/twenty_newsgroups.py", line 44, in <module>
    from ..feature_extraction.text import CountVectorizer
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/feature_extraction/__init__.py", line 10, in <module>
    from . import text
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/feature_extraction/text.py", line 28, in <module>
    from ..preprocessing import normalize
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse
  File "/home/yosri/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/utils/testing.py", line 720, in <module>
    skip_if_32bit = pytest.mark.skipif(_IS_32BIT,
AttributeError: module 'pytest' has no attribute 'mark'

**Comment by FeryET** [comment]
I'm also getting the same error. I have tried to install pymagnitude in a new miniconda environment (Python 3.7.4), but I keep getting an error. The code worked fine previously with pymagnitude in my old Anaconda environment.

> Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import model.cognitive_classifier_model
  File "/home/farhood/Projects/Cognitive-project/Final/cognitive_package/model/cognitive_classifier_model.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "/home/farhood/miniconda3/lib/python3.7/site-packages/sklearn/decomposition/__init__.py", line 10, in <module>
    from .kernel_pca import KernelPCA
  File "/home/farhood/miniconda3/lib/python3.7/site-packages/sklearn/decomposition/kernel_pca.py", line 15, in <module>
    from ..preprocessing import KernelCenterer
  File "/home/farhood/miniconda3/lib/python3.7/site-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer
  File "/home/farhood/miniconda3/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse
  File "/home/farhood/miniconda3/lib/python3.7/site-packages/sklearn/utils/testing.py", line 720, in <module>
    skip_if_32bit = pytest.mark.skipif(_IS_32BIT,
AttributeError: module 'pytest' has no attribute 'mark'


The error is coming from the compiler generating a 32bit version of pymagnitude's related stuff even though I'm using a 64bit intel cpu? I am not well-versed on how python install packages and compiles their related materials so this might be wrong.

**Comment by AjayP13** [comment]
Can you try installing on just normal Python/pip3 (not anaconda)? Does that work?

**Comment by laifi** [comment]
> Can you try installing on just normal Python/pip3 (not anaconda)? Does that work?

Yes , it works! Thanks

**Comment by cwmima** [comment]
For other people who come here with the same issue, my solution is 
```
pip3 uninstall pytest
pip3 install pytest
```
Note it's `pip3` instead of `pip` since I'm using Python3
