### ISSUE TITLE
Unable to install pymagnitude

### ISSUE THREAD

**Issue by mittalsuraj18** [plasticityai/magnitude#79]
Hi i am trying to install pymagnitude.

This is the error that i am getting

```
 Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp37-cp37m-linux_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp37-abi3-manylinux1_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp37-abi3-linux_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp36-abi3-manylinux1_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp36-abi3-linux_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp35-abi3-manylinux1_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp35-abi3-linux_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp34-abi3-manylinux1_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp34-abi3-linux_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp33-abi3-manylinux1_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp33-abi3-linux_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp32-abi3-manylinux1_x86_64.whl
    FAILED
    Trying... http://s3.amazonaws.com/magnitude.plasticity.ai/wheelhouse/pymagnitude-0.1.143-cp32-abi3-linux_x86_64.whl
    FAILED
    Done trying to download and install wheel (it didn't exist)
```

**Comment by mayankchatteron1** [comment]
same here

**Comment by DesmonDay** [comment]
I cannot install pymagnitude too.
![image](https://user-images.githubusercontent.com/20554008/95821416-6fdf7580-0d5c-11eb-8c88-040ac3c19563.png)
It stops here.

**Comment by davebulaval** [comment]
> I cannot install pymagnitude too.
> ![image](https://user-images.githubusercontent.com/20554008/95821416-6fdf7580-0d5c-11eb-8c88-040ac3c19563.png)
> It stops here.

Just wait longer, like a couple of minutes. Lots of dependacy.

**Comment by MarchaDosPescadores** [comment]
ERROR: Could not build wheels for annoy, which is required to install pyproject.toml-based projects

RROR: Failed building wheel for annoy]


RROR: Could not build wheels for pymagnitude, which is required to install pyproject.toml-based projects


    Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\<username>\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 122, in spawn_main
          exitcode = _main(fd, parent_sentinel)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\<username>\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 132, in _main
          self = reduction.pickle.load(from_parent)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      EOFError: Ran out of input
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymagnitude
Failed to build pymagnitude
ERROR: Could not build wheels for pymagnitude, which is required to install pyproject.toml-based projects

----------------------
same issue
